const NAVIGATION_LINKS = ["BIO", "PLAYGROUND", "WORK"];

const ANIMATIONS_LIST = [
  {
    id: "001",
    title: "FLOW MOTION",
    description:
      "A SMOOTH AND DYNAMIC ANIMATION THAT GIVES ELEMENTS A NATURAL FLOW EFFECT, CREATING A SEAMLESS TRANSITION EXPERIENCE. PERFECT FOR UI INTERACTIONS AND PAGE TRANSITIONS.",
    technologies: ["CSS", "JAVASCRIPT", "FRAMER MOTION", "WEBGL"],
    imagePlaceholder: "IMG Imitation",
  },
  {
    id: "002",
    title: "SCROLL REVEAL",
    description:
      "ANIMATION TRIGGERED ON SCROLL THAT REVEALS CONTENT GRACEFULLY AS THE USER MOVES THROUGH THE PAGE. ENHANCES USER ENGAGEMENT AND STORYTELLING.",
    technologies: ["CSS", "JAVASCRIPT", "GSAP"],
    imagePlaceholder: "IMG Imitation",
  },
  {
    id: "003",
    title: "BUTTON WAVE EFFECT",
    description:
      "A RIPPLED WAVE EFFECT THAT ORIGINATES FROM THE POINT OF CLICK, PROVIDING A VISUAL RESPONSE TO USER INTERACTION.",
    technologies: ["CSS", "JAVASCRIPT"],
    imagePlaceholder: "IMG Imitation",
  },
];

export {
  NAVIGATION_LINKS,
  ANIMATIONS_LIST,
};
