const TITLE_TEXT_ARR = ["HI. I’M FILIP, CREATIVE", "FRONTEND DEVELOPER", "BASED IN WATFORD."];
const AVAILABILITY_TEXT = ["OPEN", "TO", "NEW", "OPPORTUNITIES"];
const COORDINATES_ARR = ["51.6611°N", "WATFORD", "0.3970°W"];
const PARAGRAPH_TEXT1 =
  "A SELF-TAUGHT CODER, ENTHUSIASTIC ABOUT DYNAMIC AREAS OF MOTION AND ANIMATIONS. FOCUSING ON THE SMALLEST DETAILS TO ENSURE EVERYTHING IS FLAWLESS. CONSTANTLY HONING SKILLS TO CREATE SMOOTH AND ENGAGING EXPERIENCES.";
const PARAGRAPH_TEXT2 =
  "FOR THE PAST FOUR YEARS, I’VE BEEN DIVING INTO THE WORLD OF WEB/APP DEVELOPMENT, MASTERING JAVASCRIPT, REACT, AND RANGE OF OTHERS LIBRARIES ESSENTIAL FOR CREATING DYNAMIC AND FUNCTIONAL WEBSITES OR APPLICATIONS.";
const PARAGRAPH_TEXT3 =
  "I ALSO TRYING TO UNDERSTAND THE MAGIC OF WEBGL AND SHADERS WORLDS, EXPLORING HOW FAR I CAN PUSH VISUALS IN THE BROWSER. FROM BUILDING DYNAMIC 3D SCENES WITH THREE.JS & R3F TO ADDING SMOOTH INTERACTIONS WITH MOTION AND REANIMATED.";
const PARAGRAPH_TEXT4 =
  "I CURRENTLY WORKING IN REACT & REACT NATIVE, USING EXPO FOR QUICK DEVELOPMENT AND REDUX OR ZUSTAND FOR STATE MANAGEMENT. STYLED COMPONENTS & TAILWIND KEEP MY STYLES CLEAN AND MODULAR, WHILE FIREBASE HELPS ME HANDLE BACKEND TASKS WITH EASY.";
const PARAGRAPH_TEXT5 = "CONSTANTLY REFINING MY CRAFT AND EXPLORING NEW POSSIBILITIES.";
const PARAGRAPH_TEXT_ARR = [PARAGRAPH_TEXT1, PARAGRAPH_TEXT2, PARAGRAPH_TEXT3, PARAGRAPH_TEXT4, PARAGRAPH_TEXT5];

const TECH_STACK = ["JAVASCRIPT / REACT / REACT NATIVE", "R3F / THREEJS / MOTION / REANIMATED"];
const CONTACT_TITLE = ["FOR INQUIRIES, COLLABORATIONS, OR JOB"];
const FOOTER_TEXT1_ARR = ["DESIGNED & DEVELOPED BY FILIP DRZAZGA"];
const FOOTER_TEXT2_ARR = ["2@25 ALL RIGHTS RESERVED"];
const SOCIAL_LINKS = ["GITHUB", "LINKEDIN"];

const NAVIGATION_LINKS = ["BIO", "PLAYGROUND", "WORK", "LET'S TALK"];

export {
  TITLE_TEXT_ARR,
  AVAILABILITY_TEXT,
  COORDINATES_ARR,
  PARAGRAPH_TEXT_ARR,
  TECH_STACK,
  CONTACT_TITLE,
  FOOTER_TEXT1_ARR,
  FOOTER_TEXT2_ARR,
  SOCIAL_LINKS,
  NAVIGATION_LINKS,
};
